export const ROUTES = {
  NAV: {
    DEX: '/dex',
    LIQUIDITY: '/dex/liquidity',
    ASSETS: '/assets',
    EXPLORER: '/explorer',
    EXPLORER_CHARTS: '/explorer/charts',
    EXPLORER_BEAM: '/explorer/beam',
    EXPLORER_BANS: '/explorer/bans',
    EXPLORER_COUNTDOWN: '/explorer/countdown',
    EXPLORER_HEALTH: '/explorer/health',
    EXPLORER_SUPPLY: '/explorer/supply',
    EXPLORER_BRIDGE: '/explorer/bridge',
    ASSET_INFO: '/asset/:id',
    PAIR_DETAIL: '/pair/:id',
    ATOMIC_SWAPS: '/atomic-swaps',
    ASSET_SWAPS: '/asset-swaps',
    DAPPS: '/dapps',
    PRIVACY: '/privacy',
  },
};
